name: Run Appium Script on Android Emulator

on:
  schedule:
    - cron: '0 0 * * *'  # Runs the workflow daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger of the workflow

jobs:
  appium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker and Start Android Emulator
        run: |
          # Pull and run the Android emulator Docker container
          docker run --privileged -d --name android-emulator \
            -e "DEVICE=pixel" \
            -e "API_LEVEL=30" \
            -e "SOFT_RENDERING=true" \
            -p 5554:5554 -p 5555:5555 reactnativecommunity/react-native-android-emulator
          
          # Wait for the emulator to fully start
          sleep 120 # Adjust the sleep time if needed to ensure the emulator is ready

      - name: Install APK onto Emulator
        run: |
          # Copy the APK into the Docker container and install it on the emulator
          docker cp ./apk/myapp.apk android-emulator:/data/local/tmp/myapp.apk
          docker exec android-emulator adb install /data/local/tmp/myapp.apk

      - name: Install dependencies
        run: npm install

      - name: Start Appium Server
        run: |
          # Install Appium globally and start it
          npm install -g appium
          appium --log-level error --allow-cors &

      - name: Run Appium Test
        run: node appium-script.js
        env:
          APK_LOCATION: ./apk/myapp.apk
          AUTHENTICATOR_SECRET: ${{ secrets.AUTHENTICATOR_SECRET }}
          EA_EMAIL: ${{ secrets.EA_EMAIL }}
          EA_PASSWORD: ${{ secrets.EA_PASSWORD }}

      - name: Shut down Android Emulator
        run: |
          # Stop and remove the Docker container after tests are complete
          docker stop android-emulator
          docker rm android-emulator