name: Run Appium Script on Android Emulator

on:
  schedule:
    - cron: '0 0 * * *'  # Example of scheduling the workflow to run daily
  workflow_dispatch:      # Allows manually triggering the workflow

jobs:
  appium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk
          check-latest: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android Emulator and Platform Tools
        run: |
          sdkmanager --install "platform-tools" "emulator" "system-images;android-31;google_apis;x86_64"
          echo "no" | avdmanager create avd --name emulator --package "system-images;android-31;google_apis;x86_64" --device "pixel_2"
          sdkmanager --update

      - name: Set up emulator in PATH
        run: echo "${ANDROID_SDK_ROOT}/emulator" >> $GITHUB_PATH

      - name: Start Android Emulator
        run: |
          nohup emulator @emulator -no-window -no-audio -delay-adb -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock screen
        timeout-minutes: 5

      - name: Install APK onto Emulator
        run: adb -s emulator-5554 install apk/myapp.apk

      - name: Install dependencies
        run: npm install

      - name: Start Appium
        run: |
          npm install -g appium
          appium --log-level error --allow-cors &

      - name: Run Appium Test
        run: node appium-script.js
        env:
          APK_LOCATION: ./apk/app.apk
          AUTHENTICATOR_SECRET: ${{ secrets.AUTHENTICATOR_SECRET }}
          EA_EMAIL: ${{ secrets.EA_EMAIL }}
          EA_PASSWORD: ${{ secrets.EA_PASSWORD }}

      - name: Shut down Emulator
        run: adb -s emulator-5554 emu kill